#pragma config(Sensor, port5,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port11, touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port12, colourSensor,   sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          liftMotor2,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor3,          liftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          HDrive,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "TechnogearLibraryV3.0.h"



void grabRings(){
	moveForward_t(2300);
	Move_Backward_Slow(60);
  wait(50,milliseconds);
	liftArm();
	doActionUntilDistance(moveBackward_Const, 420);
	lowerArm();
}



void firstPost_1(){
	displayTextLine(line2,"getFirstPost");
	moveForward_t(2300);
	moveRight_t(2300);
	doActionUntilDistance(moveBackward_Const,300);
	doActionUntilDistance(moveLeft_Const, 450);
	grabRings();
}

void secondPost_1(){
	displayTextLine(line2,"secondPost");
	doActionUntilDistance(moveLeft_Const, 450);
//	doActionUntilDistance(turnLeft_Const, 320);
	moveForward_t(2300);
	moveRight_t(2300);
	doActionUntilDistance(moveBackward_Const,300);
	doActionUntilDistance(moveLeft_Const, 350);
	grabRings();
}

void thirdPost_1(){
	displayTextLine(line2,"secondPost");
	doActionUntilDistance(moveLeft_Const, 450);
	//doActionUntilDistance(turnLeft_Const, 320);
	moveForward_t(2300);
	moveRight_t(2300);
	doActionUntilDistance(moveBackward_Const,300);
	doActionUntilDistance(moveLeft_Const, 150);
	grabRings();
}


//collect rings from all three post
void ringCollection(){


	firstPost_1();
	secondPost_1();
	thirdPost_1();
}


task main()
{
	doActionUntilDistance(turnLeft_Const, 320);
	ringCollection();
}

