#pragma config(Sensor, port5,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port11, touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port12, colourSensor,   sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor2,          liftMotor2,    tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor3,          liftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          HDrive,        tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "moveUntilBlackFound.h"
#include "motorcommands.h"


void grabRings(){
	moveForward_t(00);
	Move_Backward_Slow(63);
  //wait(50,milliseconds);
	liftArm();
	doActionUntilDistance(moveBackward_Const, 420);
	lowerArm();
}



void getPost(){
	displayTextLine(line2,"getFirstPost");
	moveForward_t(1600);
	moveRight_t(2240);
	doActionUntilDistance(moveBackward_Const,300);
	doActionUntilDistance(moveLeft_Const, 320);
	grabRings();
}

void deposit(){
 //doActionUntilDistance(turnRight_Const, 640);
 turn90();
 turn90();
 moveBackward_t(2300);
 moveLeft_t(280);
 liftArm();
 doActionUntilDistance(moveForward_Const, 1200);
 doActionTillBlackFound(moveLeft_Const,-1);
 doActionUntilDistance(moveLeft_Const, 10);
 lowerArm();
 doActionUntilDistance(moveBackward_Const,500);

}
 void retreat(){
   //liftArm();
  wait1Msec(10);
  displayText(line1,"retreat back");
  //doActionUntilDistance(moveBackward_Const,100);
	//liftArm();
  displayText(line1,"retreat turn");
  doActionUntilDistance(turnLeft_Const, 640);
 	displayText(line1,"retreat move right");
  moveRight_t(1400);
  displayText(line1,"retreat frwd");
  //lowerArm();
 	doActionUntilDistance(moveForward_Const, 800);
 }

task main()
{
doActionUntilDistance(turnLeft_Const, 320);
getPost();
deposit();
retreat();
getPost();
deposit();
retreat();
getPost();
deposit();
}
